### ISSUE TITLE
Status of support for macros in incremental compiler

### ISSUE THREAD

**Issue by Duhemm** [sbt/sbt#1729]
This is a meta issue that gives an overview of the current state of the support for macro-enabled programs in the incremental compiler.
### Support for macros
- [x] Record dependencies on macro arguments (#1163)
- [x] Disable macro heuristic for inherited macros (#1142, #1202)
- [ ] Hooking Macrotracker in sbt (#1778, [discussion](https://groups.google.com/d/msg/sbt-dev/clIbzCp9VX8/z4IiYEZwoNEJ), [plugin](https://github.com/scalamacros/macrotracker))
- [ ] Recompile macro clients if any transitive dependency of the macro is updated ( #1836, related issue : #399, [discussion](https://groups.google.com/forum/#!topic/sbt-dev/Ub7asIeMVJA))
- [ ] Allow macro clients to depend on auxiliary (non-scala) files (#1757, [discussion](https://groups.google.com/d/msg/sbt-dev/f7fKIQSIx20/BcWJaBsY2VkJ))
### Falicities that help to support macros

These facilities make it easier to extend the kind of dependency relations that sbt knows of, and thus make it easier to implement better support for macros (or anything else that requires adding a new dependency kind).
- [x] Abstract over dependency kind in Analysis and Relations (#1340)
- [x] Don't hardcode existing relations in TextAnalysisFormats (#1572)
- [x] Abstract over dependency kind in Compile (#1736)
#### Some more words on...
- [Macrotracker](https://github.com/scalamacros/macrotracker) is a compiler plugin that registers calls to the reflection API and attaches the list of inspected ("touched") symbols to the expanded macros. These symbols can then be extracted by sbt and registered as dependencies of the macro client.
- I have a prototype of a solution for the problem of transitive dependencies of macros. It works great when the macro provider has no external dependencies. I have a solution to this problem, but I'm afraid this would hurt performance.
- Macro providers can add an attachment to the expanded macro to tell sbt that the macro client depends on an auxiliary file by giving its path. An implementation of this proposition can be found [here](https://github.com/Duhemm/sbt/tree/deps-auxiliary-files). [Example of project that uses this feature](https://github.com/Duhemm/macro-external-files)
#### Collecting the dependencies of a macro

Consider the following macro : 

``` scala
object Provider {
  def testMacro(arg: String): String = macro testMacroImpl
  def testMacroImpl(c: Context)(arg: c.Tree): c.Tree = {
    import c.universe._
    val foo = Foo.bar
    val file = scala.io.Source.fromFile("/some/file").mkString
    val result = weakTypeOf[Bar].members.sorted.toString + arg.toString + foo + file
    q"$result"
  }
}
```

and its application :

``` scala
object Client extends App {
  println(Provider.testMacro(Fizz.buzz))
}
```

After compilation, the body of `object Client` will (roughly) be equivalent to `println("List(constructor Bar, ...")`. 

However, many dependencies between `object Client` and other components exist **even though these dependencies cannot be observed at AST level after the expansion of the macro** :

`object Client` depends on...
- `Fizz.buzz` because it is an argument of the macro call (fixed, #1163)
- `Foo.bar` and on everything that `Foo.bar` depends on (and so on) (not fixed, see #399). 
- `Bar` because `Bar` is inspected using reflection. This is the kind of problem that could be solved using macro tracker.
- file `/some/file` because if its content changes, then the expansion of the macro should be different.

/cc @xeno-by @gkossakowski

**Comment by gkossakowski** [comment]
Hi @Duhemm!

Excellent overview! Thanks for collecting all references. Would you mind adding a paragraph (at the end) describing the motivation behind this work? It's probably the easiest to describe a simple macro and explain how dependencies coming from a macro are opaque to incremental compiler and why this is a problem. You don't need to discuss all facets of improved macro support, though. Just one simple example should be enough.

**Comment by Duhemm** [comment]
Hi @gkossakowski ! Thank you for the suggestion. I've just added an example that covers all problems that I mentioned previously in the post. Do you have any more comments ?

**Comment by riomus** [comment]
What is the status of this issue? It is a problem for us in our project, sbt is not recompiling macros after case class changes in the incremental compilation. I am not able to find any new pieces of information on incremental compilation and macros. In sbt 0.13 there was a macrotracker plugin, but now we are using sbt 1.0 and we need to run a clean task in order to be sure that macros are recompiled.
