### ISSUE TITLE
[sbt 1.0] Forward port 0.13 changes

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#2352]
### in *reverse* chronological order

Run the following command, and paste it at the top of the following list:

```sh
$ git log --oneline | egrep -h "\(#|pull" | head -40 | sed -e 's/^/- [ ] /'
```

- [x] 2952a2b9b Merge pull request #3370 from eed3si9n/wip/crossfix
- [x] d0db2e2dd Merge pull request #3347 from dwijnand/sbtUnchecked
- [x] 5096c3a8c Merge pull request #3361 from eed3si9n/wip/apifix
- [x] 6c8964dfd Merge pull request #3356 from eed3si9n/wip/switch
- [x] 948ff2982 Merge pull request #3329 from dwijnand/fix-scripted
- [x] 6ce09cfed Merge pull request #3265 from Rogach/0.13
- [x] 94e11fa80 Update jline dependency to 2.14.4 (#3240)

**Comment by Duhemm** [comment]
I think that all missing items have associated PRs:

> - [ ] f9dc203 Merge pull request #2343 from sbt/topic/inc-comp-stable-self 

➡️ ~~sbt/incrementalcompiler#53~~

> - [ ] f00f6fd Merge pull request #2344 from smarter/0.13-dotty

➡️ ~~sbt/incrementalcompiler#49~~, ~~sbt/librarymanagement#18~~ and ~~sbt/sbt#2393~~

> - [ ] 886b364 Merge pull request #2345 from eed3si9n/wip/testtest

➡️ ~~sbt/librarymanagement#19~~, ~~sbt/sbt#2485~~

> - [ ] bfb602c Merge pull request #2313 from sbt/wip/refix-snapshots

➡️ ~~sbt/librarymanagement#20~~, ~~sbt/sbt#2484~~

> - [ ] c1129ce Merge pull request #2335 from sbt/wip/bintrayfix

➡️ ~~sbt/librarymanagement#17~~, ~~sbt/sbt#2481~~

> - [ ] d3cb469 Merge pull request #2261 from Duhemm/fix-1171

➡️ ~~sbt/incrementalcompiler#54~~

**Comment by dwijnand** [comment]
Yep. My plan was to cut another milestone release of incremental compiler once its PRs are merged and then get the sbt one's passing Travis.

**Comment by dwijnand** [comment]
Added #2407

**Comment by dwijnand** [comment]
Added #2354

**Comment by Duhemm** [comment]
Added ~~#2413~~, ~~#2414~~ and ~~#2418~~

**Comment by Duhemm** [comment]
I'm taking care of ~~#2407~~, ~~#2354~~, ~~#2413~~, ~~#2414~~ and ~~#2418~~.
- #2407 ➡️ ~~sbt/librarymanagement#22~~ and https://github.com/Duhemm/sbt/tree/fport/adds-compatibilitywarningoptions (depends on port of #2345 (#2394)
- #2354 ➡️ ~~sbt/librarymanagement#24~~ and sbt/sbt#2420
- ~~#2413 & #2414 ➡️ sbt/incrementalcompiler#58~~
- ~~#2418 ➡️ sbt/incrementalcompiler#57~~

**Comment by Duhemm** [comment]
Added ~~#2432 ➡️ sbt/incrementalcompiler#59~~

**Comment by Duhemm** [comment]
Added
- ~~#2437 ➡️ #2455~~
- ~~#2438 ➡️ sbt/incrementalcompiler#68~~
- ~~#2448 ➡️ sbt/util#29~~
- #2453 ➡️  ~~sbt/incrementalcompiler#61~~ and #2457

**Comment by dwijnand** [comment]
Added
- ~~#2441 ➡️ sbt/incrementalcompiler#64~~

**Comment by eed3si9n** [comment]
Added
-  ~~#2335 and #2467 ➡️ #2481~~

**Comment by eed3si9n** [comment]
Added
- ~~#2345 and #2407 ➡️  #2485~~

**Comment by Duhemm** [comment]
Added #2500

**Comment by eed3si9n** [comment]
Done stuff
- [x] 251596a Merge pull request #2448 from timcharper/0.13
- [x] 49e8010 Merge pull request #2438 from Duhemm/wip/package-object-filename
- [x] 6e5082e Merge pull request #2437 from gkossakowski/nameHashing-trait-regression
- [x] a58eff8 Merge pull request #2432 from gkossakowski/nameHashing-pkg-objects
- [x] 14dcca6 Merge pull request #2418 from Duhemm/fix-2411
- [x] afa8603 Merge pull request #2407 from eed3si9n/wip/2347
- [x] 35aed2b Merge pull request #2399 from timcharper/0.13
- [x] d9f1085 Merge pull request #2371 from dwijnand/update-sbt-plugins
- [x] a5bda9d Merge pull request #2354 from eed3si9n/wip/internal
- [x] 7e88edb Merge pull request #2358 from gkossakowski/compileInterface-tests
- [x] d06b49d Merge pull request #2355 from eed3si9n/wip/scripted-more-mem
- [x] f9dc203 Merge pull request #2343 from sbt/topic/inc-comp-stable-self 
- [x] 5b7c551 Merge pull request #2349 from gkossakowski/scripted-scala-version-cleanup
- [x] f00f6fd Merge pull request #2344 from smarter/0.13-dotty
- [x] 886b364 Merge pull request #2345 from eed3si9n/wip/testtest
- [x] bcb98ab Merge pull request #2342 from sbt/wip/file-bincompat-in-io-for-pr2268
- [x] bfb602c Merge pull request #2313 from sbt/wip/refix-snapshots
- [x] b87a4ac Merge pull request #2338 from sbt/wip/nightly_launchconfig
- [x] 5ba7352 Merge pull request #2339 from sbt/wip/2325_notes
- [x] 05e5ae3 Merge pull request #2322 from dwijnand/drop-sealed-from-Append-typeclasses
- [x] c5b0c7b Merge pull request #2325 from gkossakowski/nameHashing/private-members
- [x] 7b1c19d Merge pull request #2337 from sbt/wip/nightly
- [x] c1129ce Merge pull request #2335 from sbt/wip/bintrayfix
- [x] b76db70 Merge pull request #10 from adriaanm/gkossakowski-nameHashing/private-members
- [x] d3cb469 Merge pull request #2261 from Duhemm/fix-1171
- [x] 3e56a7f Merge pull request #2315 from sbt/wip/notes2
- [x] 98fbb43 Merge pull request #2303 from jrudolph/w/2302-disable-pre-and-post-checks
- [x] 7645ca5 Merge pull request #2311 from sbt/wip/scalaversion
- [x] 8749a96 Merge pull request #2297 from sbt/wip/fix-2264
- [x] c5b7fc1 Merge pull request #2272 from Duhemm/fix-1968
- [x] 36835d7 Merge pull request #2285 from dwijnand/add-Resolver.bintraySbtRepo
- [x] 2226230 Merge pull request #2271 from Duhemm/fix-2228
- [x] afa8603 Merge pull request #2407 from eed3si9n/wip/2347
- [x] 03524e3 Merge pull request #2413 from smarter/fix/vc-return-type
- [x] e966329 Merge pull request #2414 from smarter/fix/duplicate-defs
- [x] 14dcca6 Merge pull request #2418 from Duhemm/fix-2411

**Comment by dwijnand** [comment]
Added #2637

**Comment by dwijnand** [comment]
Added #2692

**Comment by dwijnand** [comment]
Added https://github.com/sbt/sbt/pull/2731

**Comment by dwijnand** [comment]
I created a little tool to help figure this out - it's very rough around the edges, but anyways: https://github.com/dwijnand/sbt1fports

**Comment by eed3si9n** [comment]
More done stuff
- [x] 265cbd7 Fixes #2480. Workaround for Jline regression (#2570)
- [x] bc54514 Merge pull request #2569 from eed3si9n/wip/mavenrepobug
- [x] 40644ae Merge pull request #2513 from Duhemm/wip/fix-2435
- [x] b10414d Merge pull request #2564 from Duhemm/wip/fix-2518
- [x] ce611fb Merge pull request #2563 from eed3si9n/wip/macro-nonarg-dep
- [x] c35cb7f Merge pull request #2542 from eed3si9n/wip/ivypath -> https://github.com/sbt/librarymanagement/pull/46
- [x] ba72faa Merge pull request #2540 from eed3si9n/wip/synthetic
- [x] bc70ec0 Merge pull request #2169 from Duhemm/scripted-local-repo -> https://github.com/sbt/zinc/pull/92
- [x] 6125cf5 Merge pull request #2530 from dwijnand/deprecate-Build -> https://github.com/sbt/sbt/pull/2524
- [x] 9d666c5 Merge pull request #2507 from gkossakowski/self-variable-unstable -> https://github.com/sbt/zinc/pull/90
- [x] 575bc12 Merge pull request #2500 from Duhemm/wip/fix-2431 -> https://github.com/sbt/librarymanagement/pull/36 + https://github.com/sbt/sbt/pull/2593
- [x] 884da06 Merge pull request #2469 from Duhemm/wip/fix-2460 -> sbt/util#41 + #2712
- [x] 65201a5 Merge pull request #2474 from dwijnand/bump-versions
- [x] 260aa76 Merge pull request #2471 from eed3si9n/wip/0.13.10-merge
- [x] d3962a0 Merge pull request #2441 from Duhemm/wip/fix-2436 -> https://github.com/sbt/zinc/pull/64
- [x] 6f072f8 Merge pull request #2443 from eed3si9n/wip/2427 -> https://github.com/sbt/sbt/pull/2581
- [x] cdb52e9 Merge pull request #2430 from Duhemm/wip/fix-2428 -> https://github.com/sbt/sbt/pull/2581
- [x] e41859f Merge pull request #2440 from cunei/toni-output-jars -> sbt/zinc#109
- [x] a92e509 Merge pull request #2419 from eed3si9n/wip/2415
- [x] e966329 Merge pull request #2414 from smarter/fix/duplicate-defs -> sbt/zinc#65
- [x] 03524e3 Merge pull request #2413 from smarter/fix/vc-return-type -> sbt/zinc#65
- [x] 14dcca6 Merge pull request #2418 from Duhemm/fix-2411 -> sbt/zinc#95
- [x] 3958511 Merge pull request #2409 from dwijnand/tweak-0.13.10-notes
- [x] 213dc87 Merge pull request #2467 from eed3si9n/wip/jcenter -> #2481
- [x] 7530878 Merge pull request #2412 from smarter/patch-1
- [x] e4926da Merge pull request #2453 from retronym/topic/sourcepath -> sbt/zinc#61 + sbt/zinc#73 + sbt/zinc#112

**Comment by eed3si9n** [comment]
More done stuff

- [x] a58b184 Merge pull request #2828 from eed3si9n/wip/thedude
- [x] 55e2b56 Merge pull request #2826 from vpetro/bump-giter8resolver-version
- [x] bbc7063 Merge pull request #2767 from avdv/fix-2766-sourceFile-null
- [x] 47a71c0 Merge pull request #2794 from dwijnand/212
- [x] 38cfb62 Merge pull request #2764 from dwijnand/deprecate-tuple-enrich
- [x] af2056b Merge pull request #2784 from eed3si9n/wip/show_dep
- [x] 85f9189 Merge pull request #2827 from eed3si9n/wip/mediator_fix
- [x] 2a4e955 Merge pull request #2782 from bantonsson/lazily-concatenate-failed-errors
- [x] a6cfb52 Merge pull request #2780 from eed3si9n/wip/template_resolver
- [x] 0dfd409 Added CrossVersion.patch which strips off -bin-suffix. (#2757)
- [x] f860d5e Recycle classloaders to be anti-hostile to JIT: Notes (#2756)
- [x] 9598884 Merge pull request #2755 from dwijnand/show-seq-0.13
- [x] b4bc9f1 Merge pull request #2754 from retronym/ticket/SD-232-2 > (Zinc part is done: https://github.com/sbt/zinc/pull/196, we still need Defaults.scala on sbt/sbt)
- [x] 86670ca Add back addPluginResolvers (#2749)
- [x] 79b0fbb Merge pull request #2746 from dwijnand/scalas-silent
- [x] a572af0 Merge pull request #2745 from dwijnand/0.13.13-notes
- [x] 8f2a5a6 Merge pull request #2742 from eed3si9n/wip/early2
- [x] 4fa4bda Merge pull request #2738 from eed3si9n/wip/extra_rename
- [x] 0a13ac1 Merge pull request #2730 from dwijnand/wip/forked_test
- [x] 40b0b82 Merge pull request #2731 from dwijnand/wildcard-exclusions
- [x] 16a6906 Deprecate the old operators `<<=`, `<+=`, and `<++=` (#2716) > https://github.com/sbt/sbt/pull/2711
- [x] cd216a2 Backport style changes in scripted tests and Defaults.scala (#2715)
- [x] d0ce0ce Merge pull request #2717 from eed3si9n/wip/plugin
- [x] 6631456 Deprecate .value extension method from input tasks (#2709)
- [x] 2395496 Merge pull request #2708 from Duhemm/wip/fix-2707 -> #2712 
- [x] 2407815 Merge pull request #2705 from eed3si9n/wip/new_command
- [x] 5b70e9f Merge pull request #2703 from milessabin/topic/scala-artifacts-fixed -> https://github.com/sbt/librarymanagement/pull/50
- [x] bf7918f Merge pull request #2692 from eed3si9n/wip/2686
- [x] 6c8555c Merge pull request #2681 from pauldraper/pauldraper-forked-test-group
- [x] e843957 Merge pull request #2682 from xuwei-k/aggregate
- [x] 9ea9abf Merge pull request #2659 from dwijnand/log-recompile-on-macro-opt  -> sbt/zinc#143
- [x] c073558 Merge pull request #2653 from anatolydwnld/depends-on-build-sbt-two
- [x] aa5d8c1 Merge pull request #2642 from eed3si9n/wip/2002
- [x] 18568dd Merge pull request #2637 from eed3si9n/wip/recompile_on_macro_log -> sbt/zinc#143
- [x] 9dcc852 Merge pull request #2634 from milessabin/topic/scala-organization > https://github.com/sbt/librarymanagement/pull/44
- [x] bb332fa Merge pull request #2630 from eed3si9n/wip/loadperf
- [x] 9849dff Merge pull request #2628 from Duhemm/wip/workaround-2620 > https://github.com/sbt/librarymanagement/pull/43
- [x] 74510bc Merge pull request #2603 from ekrich/wip/native-script
- [x] 1880173 Merge pull request #2557 from smarter/simplify/value-class
- [x] 74d8a57 Merge pull request #2583 from eed3si9n/wip/2523
- [x] 6a0c5c6 Fixes #2573 (#2574) Fixes dependency-management /cached-resolution-configurations

**Comment by eed3si9n** [comment]
More done stuff

- [x] 5c85acb Merge pull request #3215 from eed3si9n/wip/moduleid
- [x] 77f85d6 Merge pull request #3204 from eed3si9n/wip/eviction2
- [x] 0ca24b6 Merge pull request #3202 from eed3si9n/wip/eviction
- [x] b917001 Merge pull request #3194 from dwijnand/deprecate-removed-toError
- [x] 9ecc7db Merge pull request #3179 from eed3si9n/wip/zero
- [x] 762a0e7 Merge pull request #3155 from jameskoch/bug-fix
- [x] 87db0e1 Merge pull request #3152 from smarter/fix/dotty-scalaBinaryVersion
- [x] 3ea9bbb Merge pull request #3153 from dwijnand/kill-enter-to-stay-in-shell
- [x] f9c0187 Merge pull request #3147 from dwijnand/warn-less
- [x] 4ab11d7 Merge pull request #3133 from eed3si9n/wip/sbtcrossbuilding
- [x] f64ce4e Merge pull request #3135 from eed3si9n/wip/plusequals
- [x] 76fe21e Merge pull request #3134 from eed3si9n/wip/zipexception
- [x] 1fe99df Merge pull request #3089 from eed3si9n/wip/slash
- [x] c31dfda Merge pull request #3088 from eed3si9n/wip/windows_file
- [x] ce0f558 Merge pull request #3035 from dwijnand/notify-less
- [x] 7f2bf7c Merge pull request #3025 from dwijnand/sbt.version
- [x] 9c2636e Merge pull request #3017 from eed3si9n/wip/NumberFormatException
- [x] 4de2d50 Merge pull request #3008 from dwijnand/fix/3004/false-positive-executing-in-batch-mode
- [x] 32bf2ef Merge pull request #3015 from smarter/0.13
- [x] a7413f6 Merge pull request #3002 from eed3si9n/wip/notes
- [x] 1efe482 Merge pull request #3001 from dwijnand/fishbone-to-guide
- [x] 59030cf Merge pull request #2999 from eed3si9n/wip/bump_jline
- [x] cc19d51 Merge pull request #2961 from ekrich/wip13/fix-2551
- [x] bce9679 Merge pull request #2993 from eed3si9n/wip/offline_boot
- [x] a3d776c Merge pull request #2996 from dwijnand/stay-in-shell
- [x] 0130e97 Merge pull request #2972 from haochi/0.13
- [x] aa1355c Merge pull request #3014 from larsrh/issue/3010
- [x] 7e35049 Merge pull request #2959 from eed3si9n/wip/lowerbound
- [x] b646662 Merge pull request #2943 from eed3si9n/backport/generators
- [x] 18f0e56 Merge pull request #2952 from dwijnand/notes
- [x] 756151f Merge pull request #2951 from retronym/topic/java9
- [x] 33e7cbc Merge pull request #2908 from dwijnand/fix-triggeredBy
- [x] e851cfc Merge pull request #2902 from smarter/auto-dotty-bridge
- [x] 55efa89 Merge pull request #2903 from smarter/fix/dotty-nightlies
- [x] 10b71ef Merge pull request #2897 from smarter/fix/scala-bootstrap
- [x] c223dcc Merge pull request #2854 from ashleymercer/0.13-junit-skipped
- [x] 5141a45 Merge pull request #2855 from eed3si9n/wip/buildkey_fix

**Comment by dwijnand** [comment]
Done.
