### ISSUE TITLE
Add MiMa to sbt modules

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#2383]
Much like #2381 for this repo, we need to add MiMa to the following:
- [x] https://github.com/sbt/launcher
- [x] https://github.com/sbt/io
- [x] https://github.com/sbt/serialization
- [x] https://github.com/sbt/util
- [x] https://github.com/sbt/incrementalcompiler
- [x] https://github.com/sbt/librarymanagement

**Comment by dwijnand** [comment]
@eed3si9n From http://www.scala-sbt.org/0.13/docs/Modularization.html is https://github.com/sbt/serialization also part of 1.0? Or is it part of the server-client architecture?

**Comment by eed3si9n** [comment]
sbt/serialization is used already by 0.13 as part of the implementation, so it's similar to sbt/util.
It might take on larger roll if sbt server becomes the default way to run sbt.

**Comment by dwijnand** [comment]
I see thanks.

**Comment by dwijnand** [comment]
I've created pull requests for all of these. Once they're merged I'll close this ticket.

**Comment by dwijnand** [comment]
All been merged. Done.
