### ISSUE TITLE
Forward port (or not) changes in wip/old-1.0

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#2384]
We have a number of changes on the https://github.com/sbt/sbt/compare/wip/old-1.0 branch.

We should decide whether we want to keep the change or not for 1.0:
- [ ] #913 proc interpolator + `ProcessBuilder.lines` workaround. Fixes #819
- [ ] #944 Add option preserveExecutable to IO.copyFile and IO.copyDirectory
- [ ] #1016 Handle source, docs artifacts correctly for Ivy
- [ ] #1140 IncludeRule / ExcludeRule aliases for InclExclRule

**Comment by kzys** [comment]
On #944, shouldn't be the default behavior? As a Unix user, I can't imagine the use case where I want to ignore the executable bit.

**Comment by dwijnand** [comment]
Process has been removed in sbt in favour of scala.sys.process.

The preserveExecutable changes is forward-ported in https://github.com/sbt/io/pull/53

The ivy changes were forward-ported to sbt 1.

The aliases are already present in sbt 1.0.x.
