### ISSUE TITLE
Add JDK 11 testing

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#4333]
For all modules, we should start testing on JDK 11.

- [x] https://github.com/sbt/sbt/pull/4389
- [x] https://github.com/sbt/zinc/issues/540
- [x] https://github.com/sbt/librarymanagement/pull/263
- [x] https://github.com/sbt/util/pull/181
- [x] https://github.com/sbt/io/pull/181

**Comment by He-Pin** [comment]
This is a must done now~!

**Comment by eed3si9n** [comment]
All projects are now tested using AdoptOpenJDK JDK 11.
