### ISSUE TITLE
Port macros to Scala 3.x

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#6195]
We should enumerate all macro usages and implement Scala 3.x equivalent/alternatives

### Def.x

- [ ] `def task[T](t: T): Def.Initialize[Task[T]] = macro taskMacroImpl[T]` - https://github.com/sbt/sbt/blob/v1.4.4/main-settings/src/main/scala/sbt/Def.scala#L232
- [ ] `def taskDyn[T](t: Def.Initialize[Task[T]]): Def.Initialize[Task[T]] = macro taskDynMacroImpl[T]`
- [ ] `def setting[T](t: T): Def.Initialize[T] = macro settingMacroImpl[T]`
- [ ] `def settingDyn[T](t: Def.Initialize[T]): Def.Initialize[T] = macro settingDynMacroImpl[T]`
- [ ] `def inputTask[T](t: T): Def.Initialize[InputTask[T]] = macro inputTaskMacroImpl[T]`
- [ ] `def inputTaskDyn[T](t: Def.Initialize[Task[T]]): Def.Initialize[InputTask[T]] = macro inputTaskDynMacroImpl[T]`
- [ ] `def taskIf[T](a: T): Def.Initialize[Task[T]] = macro taskIfMacroImpl[T]`
- [ ] `def settingKey[T](description: String): SettingKey[T] = macro std.KeyMacro.settingKeyImpl[T]`
- [ ] `def taskKey[T](description: String): TaskKey[T] = macro std.KeyMacro.taskKeyImpl[T]`
- [ ] `def inputKey[T](description: String): InputKey[T] = macro std.KeyMacro.inputKeyImpl[T]`

### Structure

- [ ] SettingKey `final def :=(v: T): Setting[T] = macro std.TaskMacro.settingAssignMacroImpl[T]` - https://github.com/sbt/sbt/blob/v1.4.4/main-settings/src/main/scala/sbt/Structure.scala#L74
- [ ] `final def +=[U](v: U)(implicit a: Append.Value[T, U]): Setting[T] = macro std.TaskMacro.settingAppend1Impl[T, U]`
- [ ] `final def ++=[U](vs: U)(implicit a: Append.Values[T, U]): Setting[T] = macro std.TaskMacro.settingAppendNImpl[T, U]`
- [ ] `final def <+=[V](v: Initialize[V])(implicit a: Append.Value[T, V]): Setting[T] = macro std.TaskMacro.fakeSettingAppend1Position[T, V]`
- [ ] `final def <++=[V](vs: Initialize[V])(implicit a: Append.Values[T, V]): Setting[T] = macro std.TaskMacro.fakeSettingAppendNPosition[T, V]`
- [ ] `final def -=[U](v: U)(implicit r: Remove.Value[T, U]): Setting[T] = macro std.TaskMacro.settingRemove1Impl[T, U]`
- [ ] `final def --=[U](vs: U)(implicit r: Remove.Values[T, U]): Setting[T] = macro std.TaskMacro.settingRemoveNImpl[T, U]`
- [ ]  `final def ~=(f: T => T): Setting[T] = macro std.TaskMacro.settingTransformPosition[T]`
- [ ] `def +=[U](v: U)(implicit a: Append.Value[T, U]): Setting[Task[T]] = macro std.TaskMacro.taskAppend1Impl[T, U]`
- [ ] `def ++=[U](vs: U)(implicit a: Append.Values[T, U]): Setting[Task[T]] = macro std.TaskMacro.taskAppendNImpl[T, U]`
- [ ] `def <+=[V](v: Initialize[Task[V]])(implicit a: Append.Value[T, V]): Setting[Task[T]] = macro std.TaskMacro.fakeTaskAppend1Position[T, V]`
- [ ] `def <++=[V](vs: Initialize[Task[V]])(implicit a: Append.Values[T, V]): Setting[Task[T]] = macro std.TaskMacro.fakeTaskAppendNPosition[T, V]`
- [ ] `final def -=[U](v: U)(implicit r: Remove.Value[T, U]): Setting[Task[T]] = macro std.TaskMacro.taskRemove1Impl[T, U]`
- [ ] `final def --=[U](vs: U)(implicit r: Remove.Values[T, U]): Setting[Task[T]] = macro std.TaskMacro.taskRemoveNImpl[T, U]`
- [ ] `final def :=(v: T): Setting[InputTask[T]] = macro std.TaskMacro.inputTaskAssignMacroImpl[T]`
- [ ] `final def ~=(f: T => T): Setting[InputTask[T]] = macro std.TaskMacro.itaskTransformPosition[T]`
- [ ] DefinableSetting `private[sbt] final def :==(app: S): Setting[S] = macro std.TaskMacro.settingAssignPure[S]`
- [ ] `final def <<=(app: Initialize[S]): Setting[S] = macro std.TaskMacro.fakeSettingAssignPosition[S]`
- [ ] `private[sbt] def :==(app: S): Setting[Task[S]] = macro std.TaskMacro.taskAssignPositionPure[S]`
- [ ] `private[sbt] def ::=(app: Task[S]): Setting[Task[S]] = macro std.TaskMacro.taskAssignPositionT[S]`
- [ ] `def :=(v: S): Setting[Task[S]] = macro std.TaskMacro.taskAssignMacroImpl[S]`
- [ ] `def ~=(f: S => S): Setting[Task[S]] = macro std.TaskMacro.taskTransformPosition[S]`
- [ ] `def <<=(app: Initialize[Task[S]]): Setting[Task[S]] = macro std.TaskMacro.fakeItaskAssignPosition[S]`

### InputWrapper

- [ ] `def taskValue: Task[T] = macro InputWrapper.taskValueMacroImpl[T]` - https://github.com/sbt/sbt/blob/v1.4.4/main-settings/src/main/scala/sbt/std/InputWrapper.scala#L194
- [ ] `def value: T = macro InputWrapper.valueMacroImpl[T]`
- [ ] `def parsed: T = macro ParserInput.parsedMacroImpl[T]`
- [ ] `def evaluated: T = macro InputWrapper.valueMacroImpl[T]`
- [ ] `def inputTaskValue: InputTask[T] = macro InputWrapper.inputTaskValueMacroImpl[T]`
- [ ] `def parsed: Task[T] = macro ParserInput.parsedInputMacroImpl[T]`
- [ ] `def previous(implicit format: sjsonnew.JsonFormat[T]): Option[T] = macro InputWrapper.previousMacroImpl[T]`

### others

- [ ] `def ignoreResult[T](f: => T): Unit = macro Macro.ignore` - https://github.com/sbt/sbt/blob/v1.4.4/internal/util-collection/src/main/scala/sbt/internal/util/Util.scala#L48
- [ ] `def fromEnclosing(): SourcePosition = macro SourcePositionMacro.fromEnclosingImpl` - https://github.com/sbt/sbt/blob/v1.4.4/internal/util-position/src/main/scala/sbt/internal/util/Positions.scala#L36
- [ ] `def settingKey[T](description: String): SettingKey[T] = macro std.KeyMacro.settingKeyImpl[T]` - https://github.com/sbt/sbt/blob/v1.4.4/main/src/main/scala/sbt/BuildSyntax.scala
- [ ] `def taskKey[T](description: String): TaskKey[T] = macro std.KeyMacro.taskKeyImpl[T]`
- [ ] `def inputKey[T](description: String): InputKey[T] = macro std.KeyMacro.inputKeyImpl[T]`
- [ ] `def project: Project = macro Project.projectMacroImpl` - https://github.com/sbt/sbt/blob/v1.4.4/main/src/main/scala/sbt/Project.scala#L984
- [ ] `def inputFileChanges: FileChanges = macro changedInputFilesImpl[T]` - https://github.com/sbt/sbt/blob/v1.4.4/main/src/main/scala/sbt/internal/FileChangesMacro.scala#L31
- [ ] `def outputFileChanges: FileChanges = macro changedOutputFilesImpl[T]`
- [ ] `def inputFiles: Seq[NioPath] = macro inputFilesImpl[T]`
- [ ] `def outputFiles: Seq[NioPath] = macro outputFilesImpl[T]`
- [ ] `def config(name: String): Configuration = macro sbt.librarymanagement.ConfigurationMacro.configMacroImpl`

- https://github.com/sbt/sbt/blob/v1.4.4/core-macros/src/main/scala/sbt/internal/util/appmacro/ContextUtil.scala
- https://github.com/sbt/sbt/blob/v1.4.4/core-macros/src/main/scala/sbt/internal/util/appmacro/Instance.scala
- https://github.com/sbt/sbt/blob/v1.4.4/main-settings/src/main/scala/sbt/std/KeyMacro.scala
- https://github.com/sbt/sbt/blob/v1.4.4/main-settings/src/main/scala/sbt/std/SettingMacro.scala
- https://github.com/sbt/sbt/blob/v1.4.4/main-settings/src/main/scala/sbt/std/TaskMacro.scala

**Comment by SethTisue** [comment]
is the plan for sbt 2.0 to be 2.13-based or 3.0-based?  cc @BalmungSan

**Comment by eed3si9n** [comment]
I don't have a concrete plan yet, but I feel like we should try to attempt the macro port sooner so we don't become really behind like sbt 0.13.
