### ISSUE TITLE
sbt in Scala 3 follow-up

### ISSUE THREAD

**Issue by adpi2** [sbt/sbt#7462]
I once wrote a list of follow-up tasks in https://github.com/sbt/sbt/pull/6746 but it mysteriously disappeared.

So I am copying it here, to keep track of the progress:
- [X] Update to Scala 3.3.1 https://github.com/sbt/sbt/pull/7440
- [X] Remove cross-compilation options from utilCommonSettings
- [X] Fix or remove cross-compilation in testingProj, utilScripted, protocolProj, stdTaskProj, logicProj,
    zincLmIntegrationProj, taskProj, sbtClientProj, runProj, mainProj, buildFileProj, completeProj, coreMacrosProj,
    mainSettingsProj, utilLogging, utilCache, actionsProj, collectionProj, commandProj, utilTracking
    (it still works in utilControl, bundledLauncherProj, scriptedPluginProj, utilRelation, utilPosition, comm) https://github.com/sbt/sbt/pull/7433
- [X] Try declare F as covariant in Execute, ExecuteProgress and PMap https://github.com/sbt/sbt/pull/7444
- [x] Try get rid of the obscure ~>| in TypeFunctions https://github.com/sbt/sbt/pull/7491
- [X] Can we drop the support of List in AList. (we can convert List to Tuple using `Tuple.fromArray(list.toArray)`) https://github.com/sbt/sbt/pull/7456
- [x] `*` in `RichOps` is hiding `*` in `StringOps`, find a fix (an overload?) https://github.com/sbt/sbt/pull/7491
- [x] In Cont.scala, use report.errorAndAbort instead of sys.error https://github.com/sbt/sbt/pull/7491
- [x] Try define `RichTaskable` as `RichTaskable[T <: Tuple](t: Tuple.Map[T, ST])` https://github.com/sbt/sbt/pull/7456
- [x] In `Structure.scala`, get rid of `Manifest`, maybe introduce `TaskTag[A]`, `InputTaskTag[A]`... https://github.com/sbt/sbt/pull/7490
- [ ] Fix todo in Settings.scala
- [x] List.scala:115-147, define `TupleK` as `type TupleK[T <: Tuple] = [F[_]] =>> Tuple.Map[T, F]` https://github.com/sbt/sbt/pull/7456
- [x] In TaskMacro.scala lines 108, 114, 122...: inline the report.errorAndAbort https://github.com/sbt/sbt/pull/7491
- [x] Fix todo in ErrorSpec.scala:38, and try uncomment test (line 43) https://github.com/sbt/sbt/pull/7492
- [x] Dependencies.scala line 94: publish eval for Scala 3.3.1 https://github.com/sbt/sbt/pull/7493
- [ ] Use eval library instead of local copy
- [x] Fix todo in SbtRefactorings.scala:96 https://github.com/sbt/sbt/pull/7494
- [x] Fix todo in Main.scala:134-135: store bootServerSocket in state https://github.com/sbt/sbt/pull/7508
- [x] Fix todo in Load.scala:746 (BSP reporter) https://github.com/sbt/sbt/pull/7517
- [x] Fix todo in Load.scala:280 https://github.com/sbt/sbt/pull/7519
- [ ] Fix todo in Opts.scala:47&53 (Sonatype OSS repos)
- [ ] Fix todo in Import.scala:301-302
- [ ] Uncomment and fix tests in ci.yml (lines 115, 121, 122, 126, 127, 129, 130, 136, 141, 143, 144, 149, 151)
- [x] Uncomment and fix tests: (ParserKey.scala, ParserSpec.scala, PluginCommandTest.scala, CompletionSpec.scala) (https://github.com/sbt/sbt/pull/7521/files)
- [x] Fix pending or commented scripted tests: (https://github.com/sbt/sbt/pull/7522)
  clean-managed, compile-clean, compile-time-only are pending
  dependency-management/artifact/build.sbt:14
  actions/cross-advanced/test:22-27
  actions/depends-on/build.sbt:5-7
  input-task-dyn, generator, run-task, task-map, src-dep-plugin are pending
  exclude-dependencies, exclude-dependencies2, pom-advanced, version-interval are pending
  no-scala-tool, auto-plugins-default-requires-jvmplugin, binary-plugin, derived, extra
  giter-8, ignore-hidden-build-files, fork-loader, non-local-main, spawn-exit, scala-instance-classloader,
  serialn test-artifact, cache-resolver, cached-resolution-classifier, deliver-artifacts
- [ ] Port or remove commented Scala 2 code in
  Types.scala, TypeFunctions.scala, Actions.scala, Def.scala (line 310, 318, 421), InputTask.scala, InputWrapper.scala (line 15, 67, 161, 221), , Instances.scala (line 38), TaskMacro.scala, IntputTaskMacro.scala (line 116), main.contra, ProjectOrigin.scala, PluginTrigger.scala, UsageTest.scala, ProjectExtra.scala, StateTransform.scala, Import.scala (line 138, 144, 159-164...)
- [ ] Remove deprecated methods in Structure.scala
- [ ] Make a community build of plugins to enable global-plugins
- [x] Port all PRs from 1.10.x
- [ ] Try get rid of Attributed in packaging. Use something like `class ClasspathEntry(path: HashedVirtualFileRef, artifact: String, moduleID: String, configuration: String, analysis: Option[String])` instead.
- [ ] Rework Continuous without DeprecatedContinuous

**Comment by eed3si9n** [comment]
Closing this for now.
